---
# install latest docker community edition

- name: Set distro release codename
  set_fact:
    distribution_release: "{{ ansible_facts['lsb']['codename'] }}"

- name: Remove conflicting packages
  apt:
    pkg:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install docker dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
    state: latest
    update_cache: true

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution_release }} stable
    state: present

- name: Install docker community edition
  apt:
    name: docker-ce
    update_cache: true
    state: present
