---
- name: Install Apache certbot plugin
  include_tasks:
    file: apache-certbot.yml
  when: webserver_stack == 'lamp'

- name: Install nginx certbot plugin
  include_tasks:
    file: nginx-certbot.yml
  when: webserver_stack == 'lemp'

- name: Install certbot standalone plugin
  include_tasks:
    file: standalone-certbot.yml
  when: webserver_stack == 'standalone'

- name: Use certbot webroot authenticator
  include_tasks:
    file: webroot-certbot.yml
  when: webserver_stack == 'webroot'
